### ISSUE TITLE
Array<int8> is misinterpreted as Array<bool>

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#141]
If one reverts the order of execution of `test_getitem_i8 --> test_getitem_bool`  to `test_getitem_bool --> test_getitem_int8`, then `i8` arrays starts to be interpreted as boolean arrays and any value different than 0 is interpreted as 1, resulting in a test failure.

diff to reproduce:
https://gist.github.com/guilhermeleobas/0747df260e2e65ba951efc92e6debf8d

It seems that this failure was introduced in https://github.com/xnd-project/rbc/pull/119

**Comment by pearu** [comment]
It is the same as #140, so closing as duplicate.
