### ISSUE TITLE
Implement support for signbit

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#152]
numba uses numpy implementation of signbit that is included in numpy RT library. However, numpy RT not available for omniscidb server.

Possible options:
- implement signbit support using the signbit functions from math library
- expose numpy RT to omniscidb server, it must not include any Python functions.bit.

The approach taken must be applicable for other functions that have similar implementations to signbit.

**Comment by guilhermeleobas** [comment]
For ufuncs, we ought to replace the implementation on `npy_mathimpl.py` like we did for `np.logaddexp` and `np.logaddexp2`. The reason for this is that once the function is registered by Numba, it becomes impossible (without changing internals) to replace the implementation. So, on `npy_mathimpl.py` we change the implementation that Numba will use. 

https://github.com/xnd-project/rbc/blob/8d576bddb5778f40f521ab1362b07112edae24f2/rbc/npy_mathimpl.py#L73-L85

**Comment by pearu** [comment]
> For ufuncs, we ought to replace the implementation on `npy_mathimpl.py` ...

Does it break numba?

**Comment by guilhermeleobas** [comment]
> > For ufuncs, we ought to replace the implementation on `npy_mathimpl.py` ...
> 
> Does it break numba?

No, but the NumPy implementation may be more precise than ours. For instance, consider the implementation for `np.nextafter`:

https://github.com/numpy/numpy/blob/6d4895cc9fe614cf3164891b1f502453312f64ca/numpy/core/src/npymath/ieee754.c.src#L400-L449

**Comment by guilhermeleobas** [comment]
Closed by https://github.com/xnd-project/rbc/pull/154
