### ISSUE TITLE
Support single cursor for multiple input columns

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#173]
The following example should work:
```

    @omnisci('int32(Column<double>, Column<bool>, RowMultiplier, OutputColumn<double>)')
    def mask_zero(x, b, m, y):
        for i in range(len(x)):
            if b[i]:
                y[i] = 0.0
            else:
                y[i] = x[i]
        return len(x)
```
Currently, one can use:
```
omnisci.sql_execute(f'select * from table(mask_zero(cursor(select f8 from {omnisci.table_name}), cursor(select b from {omnisci.table_name}), 1))')
```
which is inefficient, unreliable, and not user-friendly.

One should be able to use:
```
omnisci.sql_execute(f'select * from table(mask_zero(cursor(select f8, b from {omnisci.table_name}), 1))')
```
that fails with:
```
No match found for function signature mask_zero(<CURSOR>, <NUMERIC>)
```

**Comment by pearu** [comment]
The plan is to use the following approach:
```
    @omnisci('int32(Cursor<Column<double>, Column<bool>>, RowMultiplier, OutputColumn<double>)')
    def mask_zero2(x, b, m, y):
        for i in range(len(x)):
            if b[i]:
                y[i] = 0.0
            else:
                y[i] = x[i]
        return len(x)

    descr, result = omnisci.sql_execute(f'select * from table(mask_zero2(cursor(select f8, b from {omnisci.table_name}), 1))')
```
Notice how the types of the first input columns are tied together: `Cursor<Column<double>, Column<bool>>`.

**Comment by tmostak** [comment]
Very nice, so we can theoretically have multiple input queries with this as well, while grouping where needed.

Except for the fact that I believe we assume there is one table and feed the kernel that one table's size, and the fact that row multiplier assumes a single table, are there any blockers to allowing multi query/table input as well? (There would be lots of use cases for this).

**Comment by pearu** [comment]
> Except for the fact that I believe we assume there is one table and feed the kernel that one table's size, and the fact that row multiplier assumes a single table, are there any blockers to allowing multi query/table input as well? (There would be lots of use cases for this).

Yes, we need to consider these questions as well. I suggest proceeding with these features step by step.

**Comment by pearu** [comment]
The specification `Cursor<Column<double>, Column<bool>>` can be simplified either to the following specs:
- `Cursor<double, bool>`
- `Column<double, bool>`

The first option is preferred because it will match with the semantics used in SQL queries.
