### ISSUE TITLE
NULL support in UDFs

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#240]
Currently, UDF Array arguments support `is_null` method for null checking. However, the null checking support for other argument types needs to be verified with tests and the corresponding implementation if needed.

To resolve this issue, test the following UDFs:

```
@omnisci('T(T, T)')
def null_to_value(x, value):
    if x.isNull():  # or `is_null(x)`
        return value
    return x

@omnisci('T(T, T)')
def value_to_null(x, value):
    if x == value:
        return x.null_value  # or `null_value(x)`
    return x
```

using test table with nulls (see rbc/tests/__init__.py).

The tests must be created for all `T` in `int8, ..., int64, bool, float, double, Array<int8>, ..., Array<double>, Bytes`.

**Comment by pearu** [comment]
This issue is also about supporting Array element null values:
```
@omnisci('T(T[])', T=['double', ...])
def null_to_value(x, i, value):
    if x.is_null():  # array row is null
        return value
    if x.is_null(i)  # array element is null
        return value
    return x[i]
```

Notice that `double` null value is different from `Array<double>` item null value!

**Comment by guilhermeleobas** [comment]
As of today, the server sends null values as unsigned values. Thus, the null value of `Array<int8>` for instance is -127 and not 129.
```
{'boolean1': 1, 'boolean8': 128, 'int8': 128, 'int16': 32768, 'int32': 2147483648, 'int64': 9223372036854775808, 'uint8': 255, 'uint16': 65535, 'uint32':
 4294967295, 'uint64': 18446744073709551615, 'float32': 8388608, 'float64': 4503599627370496, 'Array<boolean8>': 129, 'Array<int8>': 129, 'Array<int16>':
 32769, 'Array<int32>': 2147483649, 'Array<int64>': 9223372036854775809, 'Array<float32>': 16777216, 'Array<float64>': 9007199254740992}
```
A quick way to get the correct value is `np.uint64(null_value).astype(signed_type)`
