### ISSUE TITLE
rbc documentation is broken

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#25]
The [api reference](https://rbc.readthedocs.io/en/latest/rbc/api.html) page on Read the Docs seems to be broken.

**Comment by pearu** [comment]
It looks like #26 was not sufficient for the fix.

See https://readthedocs.org/projects/rbc/builds/10412895/ that might contain info why the API docs are not generated.

**Comment by guilhermeleobas** [comment]
I think we're missing a '.readthedocs.yml' config file. See:
https://github.com/readthedocs/readthedocs.org/issues/3634

**Comment by pearu** [comment]
PR #27 gives:
```
Collecting package metadata: ...working... done
Solving environment: ...working... done
Killed

Command killed due to excessive memory consumption
```
https://readthedocs.org/projects/rbc/builds/10414387/

If this is due to conda then we could also rely on pip.

**Comment by guilhermeleobas** [comment]
That's unfortunate. I will open another PR using pip instead of conda.

**Comment by guilhermeleobas** [comment]
It's working now! I will close this issue.
