### ISSUE TITLE
Document the usage of ColumnList attributes.

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#312]
Hi Pearu, can you write some docs as well explaining how to use and internal attributes about ColumnList? You can put those under `doc/` folder. Don't worry if the docs don't build as expected, I can fix them in another PR.

_Originally posted by @guilhermeleobas in https://github.com/xnd-project/rbc/issues/306#issuecomment-799621838_

**Comment by guilhermeleobas** [comment]
Done in #309
