### ISSUE TITLE
test_numpy_function[np.logaddexp-gpu] fails when following test_numpy_function[np.logaddexp-cpu]

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#337]
Using CUDA enabled omniscidb server (omniscidb-internal PR 5561, master should be the same).

The following test runs pass:
```
pytest -sv rbc/tests/test_omnisci_math.py -x -k test_numpy_function[np.logaddexp-cpu
pytest -sv rbc/tests/test_omnisci_math.py -x -k test_numpy_function[np.logaddexp-gpu
```
but this fails:
```
pytest -sv rbc/tests/test_omnisci_math.py -x -k test_numpy_function[np.logaddexp-
```
with
```
rbc.errors.OmnisciServerError: SQL Error: From line 1, column 18 to line 1, column 38: No match found for function signature logaddexp(<NUMERIC>, <NUMERIC>)
```
and a warning message:
```
/home/pearu/git/xnd-project/rbc/rbc/irtools.py:311: UserWarning: Skipping logaddexp__gpu_0 that uses undefined function `log1p`
```
So, it looks like GPU version of `logaddexp` uses CPU version of `log1p` under neath. @guilhermeleobas , any ideas?

**Comment by guilhermeleobas** [comment]
Numba is caching the CPU version. See:
https://github.com/numba/numba/blob/d0ca288f24eccff3ba1f86e38f0de07a717f8d4c/numba/core/base.py#L856-L857
