### ISSUE TITLE
Remove `pass_by_value` property when omnisci v5.9 is released

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#342]
In OmniSciDB v5.7, we stopped using `pass_by_value` property and all columns are passed by reference. Since this change breaks older versions of OmniSciDB, we will keep this option around for a couple more releases.

xref: https://github.com/xnd-project/rbc/pull/341

**Comment by pearu** [comment]
The issue may be outdated: https://github.com/omnisci/omniscidb-internal/pull/5765

**Comment by guilhermeleobas** [comment]
We might want to decide to remove `pass_by_value` option after a few releases of OmniSciDB
