### ISSUE TITLE
Numba 0.54 generates empty body in some cases

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#354]
Tests affected:
* test_omnisci_array_methods.py::test_ndarray_methods[mean_empty_int]
* test_omnisci_array_methods.py::test_ndarray_methods[min_empty]
* test_omnisci_array_operators.py::test_array_operators[countOf]

cc @brenocfg

**Comment by guilhermeleobas** [comment]
I can't reproduce this error anymore

**Comment by brenocfg** [comment]
Yep, tried it out and tests seem to work fine with numba 0.54, closing this. We can reopen if it occurs again at some point.

**Comment by pearu** [comment]
Does the issue exist with some older RC of numba 0.54?

**Comment by brenocfg** [comment]
> Does the issue exist with some older RC of numba 0.54?

Does not seem like it. I tried all three RCs and tests work fine on all of them.
