### ISSUE TITLE
rbc 0.6.0 release plan

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#356]
For rbc 0.6.0, the following issues/PRs must be resolved/landed:

- [x] https://github.com/omnisci/omniscidb-internal/pull/5765 - required to support `set_output_row_size` within rbc
- [x] https://github.com/xnd-project/rbc/pull/341 - implements `set_output_row_size` support in rbc
- [x] https://github.com/xnd-project/rbc/issues/357
     + [x] https://github.com/xnd-project/rbc/pull/358
- [x] Optionally, https://github.com/xnd-project/rbc/pull/353 - implements numba 0.54 support
- [x] Run rbc master branch tests against omniscidb-internal master branch:
     + [x] CPU-only omniscidb
     + [x] CUDA enabled omniscidb
- [x] How to update rbc version? In short, `./utils/tag-version 0.6.0` does it, see release instructions for more details.

For release, follow instructions in https://github.com/xnd-project/rbc/wiki/How-to-do-a-new-release-of-RBC

**Comment by guilhermeleobas** [comment]
It looks like the only blocker for this release is https://github.com/xnd-project/rbc/pull/341

**Comment by guilhermeleobas** [comment]
RBC master branch tests pass with both CPU-only and CUDA enabled omniscidb.

**Comment by pearu** [comment]
- [x] 0.6.0 is available in https://pypi.org/project/rbc-project/
- [x] 0.6.0 is available in https://github.com/conda-forge/rbc-feedstock/
