### ISSUE TITLE
Make libm functions "visible" to rbc

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#36]
Numba implement some function as calls to [libm](https://en.wikipedia.org/wiki/C_mathematical_functions) functions. For instance, consider the case below:

```python
omni.reset()

@omni('double(double)')
def fn(x):
  return np.log1p(x)

omni.register()
```

```llvm
; ModuleID = 'rbc.irtools.compile_to_IR'
source_filename = "<string>"
target triple = "x86_64-unknown-linux-gnu"

@"_ZN08NumbaEnv8__main__6fn$242Ed" = common local_unnamed_addr global i8* null

; Function Attrs: nounwind readonly
declare double @log1p(double) local_unnamed_addr #0

; Function Attrs: nounwind readonly
define double @fn_dadA(double %.1) local_unnamed_addr #0 {
entry:
  %.25.le.i = tail call double @log1p(double %.1) #1, !noalias !0
  ret double %.25.le.i
}

attributes #0 = { nounwind readonly }
attributes #1 = { nounwind }

!0 = !{!1}
!1 = distinct !{!1, !2, !"_ZN8__main__6fn$242Ed: %retptr"}
!2 = distinct !{!2, !"_ZN8__main__6fn$242Ed"}
```

`np.log1p` is translated to a call to libM `log1p`. In this case, in the step of getting function dependencies, rbc will mark the call as "undefined" and will raise an error. As a workaround, I propose we add a whitelist of functions available on libm.

## To-Do list

- [x] Add libm list
- [ ] Retrieve list from server

**Comment by pearu** [comment]
I agree with creating a whitelist.

In the future, the whitelist should be filled with names retrieved from the server.
