### ISSUE TITLE
Support `enumerate` for UD[T]F

### ISSUE THREAD

**Issue by tupui** [xnd-project/rbc#420]
Classic Python grammar should be supported. `enumerate` is not supported in UD[T]F.

**Comment by pearu** [comment]
Supporting `enumerate` depends on whether numba supports it in nopython mode or not.

**Comment by tupui** [comment]
Seems like it no? https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#built-in-functions

Do we have such a list of features/grammar that we support?
