### ISSUE TITLE
LLVM ERROR: Symbol not found: _allocate_varlen_buffer

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#75]
For some reason, a prefix `_` is being added to the function name.

**Comment by pearu** [comment]
Do you have a reproducer?

**Comment by guilhermeleobas** [comment]
The test from https://github.com/xnd-project/rbc/issues/74 produces this error

**Comment by guilhermeleobas** [comment]
It is good to note that this only happens if a jitted function calls another that returns an array. For instance, calling `get_array` works just fine, but `foo` will not even compile:

```python
@omnisci('int64[](int64)')
def get_array(size):
    return Array(size, 'int64')

@omnisci('int64[](int64)')
def foo(size):
    a = get_array(size)
    return a
```

**Comment by guilhermeleobas** [comment]
Update for future reference: this error is related to an UDF being registered again in the cleanup part of the test.

**Comment by pearu** [comment]
It turns out that the fix in PR #83 was not sufficient:
```
pytest -sv rbc/tests/test_omnisci*.py -x
...
rbc/tests/test_omnisci_array.py::test_np_cumsum PASSED
rbc/tests/test_omnisci_array_methods.py::test_ndarray_methods[fill] LLVM ERROR: Symbol not found: allocate_varlen_buffer
```
Notice that the python process exits at the LLVM ERROR.

When disabling `test_np_cumsum`, other tests pass ok.

**Comment by pearu** [comment]
The `LLVM ERROR` is triggered from calling` compiler.compile_extra`.

**Comment by guilhermeleobas** [comment]
Error is raised on [`llvmlite::finalize_object`](https://github.com/numba/llvmlite/blob/c4f5a085c9f9c7a192579b02a11347bfc2ac768b/llvmlite/binding/executionengine.py#L87) method.

**Comment by guilhermeleobas** [comment]
As a quick workaround, one can replace the `allocate_varlen_buffer` function by `calloc`. In the long term, it would be good to use functions defined by Omnisci.

A few items to investigate:
1) Do the order of declared functions matter on LLVM IR?
2) Is the function `allocate_varlen_buffer` being declared more than once?
3) Find the usage of `locals` on `compiler.compile_extra`
