### ISSUE TITLE
Always initialize the array with a default value

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#76]
The following code will crash the server due to memory not being initialized:
```python
@omnisci('int64[](int64)')
def foo(sz):
    return Array(sz, 'int64')
```

My proposal would be to initialize arrays with a default value for the type or fill it zeros: `memset(0, sz, len(T) * sz)`

**Comment by pearu** [comment]
I think it should be optional. For instance, if a subsequent code is going to fill array anyway, then calling memset is a waste. We could support the following constructions:
```
Array(sz, dtype)
Array(sz, dtype, fillvalue)
```

On the other hand, could we reuse more of numpy API so that the following constructions would work:
```
np.empty(sz)
np.zeros(sz)
np.ones(sz)
```
etc.? It would be ideal if end-users would not need to use `Array` at all, if possible, so that the defined functions could be backend agnostic and one could call these on numpy arrays as well locally.

**Comment by guilhermeleobas** [comment]
Great idea. I tried to implement `np.zeros` but faced a problem to make numba picking the right implementation. The overload mechanism let us select the correct implementation based on the input types. Since numba already overloads `np.zeros`, any call to it will use the default numba implementation, not the one I did for Omnisci Arrays.

As a workaround, we might have two options:

1. Dig into numba internals and replace the implementation

2. Mimic the NumPy api

```python
def zeros(shape, dtype=types.int64):
    pass

@overload(zeros)
def impl_zeros(shape, dtype=types.int64)
    def impl(shape, dtype=types.int64):
        ...
    return impl


# usage
import omnisci_array as omni  # or something similar
@omnisci('int64[](int64)')
def test_np_zeros(size):
    return omni.zeros(size)
```

**Comment by pearu** [comment]
Yes, the second approach would be preferred. However, consider the example:
```
import numpy as np
@omnisci('int64[](int64)')
def test_np_zeros(size):
    return np.zeros(size)
```
where the `omnisci` decorator re-maps `np` to `rbc.omnisci_numpy_api` (or similar) that implements NumPy API for omnisci arrays. Here is a prototype of how to implement the re-mapping:
```
>>> import numpy as np
>>> def foo():
...     return np.zeros(3)
... 
>>> foo()
array([0., 0., 0.])
>>> class MyNamespace:
...     def zeros(self, size):
...         return [0] * size
... 
>>> omnisci_numpy_api = MyNamespace()
>>> foo.__globals__['np'] = omnisci_numpy_api
>>> foo()
[0, 0, 0]
```

**Comment by guilhermeleobas** [comment]
Do you know if it is possible to achieve this with Numba?

**Comment by guilhermeleobas** [comment]
From this [thread](https://github.com/numba/numba/issues/5043), I don't think it is possible to replace/override an overloaded implementation in Numba. Should we stick with what I proposed in https://github.com/xnd-project/rbc/pull/85:

```python
# omnisci_array.py

def full(shape, fill_value, dtype):
    pass

@overload(full)
def full_impl(shape, fill_value, dtype):
    # impl here

# test.py
import omisci_array as omni

@omnisci('int64[](int64, int64)')
def test(size, fill_value):
    return omni.full(size, fill_value, 'int64')
```
