### ISSUE TITLE
Running omnisci tests is slow

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#79]
Investigate where is the boddle-neck of running omniscidb queries containing UDF calls.

For instance, running the 14 tests in test_ndarray_methods takes about 17 seconds (omniscidb server runs on the same host).

**Comment by guilhermeleobas** [comment]
In the way we structure tests, Numba will compile all `ndarray_{method}` tests every single time a test is executed. That's why this file is too slow.

**Comment by pearu** [comment]
Yes, this can be the case here. We can restructure the tests as follows:
```
ndarray_methods = [
    ('fill', 'double[](int64, double)', (5, 4), [4.0, 4.0, 4.0, 4.0, 4.0]),
   ... ]
...
def test_ndarray_methods(omnisci, method, signature, args, expected):
    omnisci.reset()
    from rbc.omnisci_array import Array

    def ndarray_fill(size, v):
        a = Array(size, 'double')
        a.fill(v)
        return a
    ...

    omnisci(signature)(eval('ndarray_{method}'))

    query = 'select ndarray_{method}'.format(**locals()) + \
            '(' + ', '.join(map(str, args)) + ')'
    _, result = omnisci.sql_execute(query)
    ...
```
