### ISSUE TITLE
Can UDF accept scalar parameter provided by user at runtime (immediate value) in SQL

### ISSUE THREAD

**Issue by YanzheL** [xnd-project/rbc#9]
For example, user call UDF `count_same(x,y)` to count the number of items in an array column that equals to the value `3` provided by user at runtime.

```sql
SELECT count_same(3, an_array_column) FROM some_table;
```

Can I define the UDF as this?

```python
@omnisci('i32(i32, i32[])')
def count_same(x,y):
    ct = 0
    for i in y:
        if x ^ i == 0:
            ct +=1
    return ct
```

From your examples, it seems that the parameter of UDF can only be a column, not a runtime scalar (aka. immediate value).

To make it further, if user can provide immediate scalar as parameter, then can we provide immediate array as parameter?

For example, get the intersection of `{1,2,3,4}` and `an_array_column` :

```sql
SELECT intersection({1,2,3,4}, an_array_column) FROM some_table;
```

**Comment by pearu** [comment]
Yes, you can define `count_same` but one must use explicit for-loop:
```
@omnisci('i32(i32, i32[])')
def count_same(x,y):
    ct = 0
    for i_ in range(len(y)):
        i = y[i_]
        if x ^ i == 0:
            ct +=1
    return ct
```

The example SQL expression appears to be illegal for omnisci and I am not sure what is the correct way to specify array literals in omnisci SQL expressions.. From the RBC side, I see no obstacles why the example would not work.

**Comment by pearu** [comment]
```
SELECT intersection(array[1,2,3,4], an_array_column) FROM some_table;
```
ought to work.

**Comment by YanzheL** [comment]
Thanks!
I'll try it later.

**Comment by pearu** [comment]
Closing. Feel free to open the issue if something does not work here.
